[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.21.1"
loom = "1.13-SNAPSHOT"

fabric_loader = "0.18.1"
yarn = "build.3"
fabric_api = "0.116.7"

trinkets = "3.10.0"
# lib39 = "1.5.0-experimental6.1"
emi = "1.1.22"

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "loom" }
